# Generated by Django 3.1.1 on 2020-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_person_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
