# Generated by Django 3.1.1 on 2020-11-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201118_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='value',
            new_name='num',
        ),
    ]
